In [51]:
import csv
import numpy as np
from pprint import pprint as pp

### NUMPY

In [52]:
# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f)) #its a list
# remove the header row
taxi_list = taxi_list[1:]
taxi_list[0:1] #show  1st eelement

[['2016',
  '1',
  '1',
  '5',
  '0',
  '2',
  '4',
  '21.00',
  '2037',
  '52.00',
  '0.80',
  '5.54',
  '11.65',
  '69.99',
  '1']]

In [53]:
#convert all numbers to float type
c_taxi_list = [ [ float(f) for f in r ] for r in taxi_list]
c_taxi_list[0]

[2016.0,
 1.0,
 1.0,
 5.0,
 0.0,
 2.0,
 4.0,
 21.0,
 2037.0,
 52.0,
 0.8,
 5.54,
 11.65,
 69.99,
 1.0]

In [54]:
taxi = np.array(c_taxi_list)  #create numpy array
taxi.shape

(89560, 15)

In [55]:
#first 10 rows
taxi_ten = taxi[:10]
pp(taxi_ten[0,]) #first row
pp(taxi_ten[0:2,0:2]) #first 2 rows first two coluns

array([  2.01600000e+03,   1.00000000e+00,   1.00000000e+00,
         5.00000000e+00,   0.00000000e+00,   2.00000000e+00,
         4.00000000e+00,   2.10000000e+01,   2.03700000e+03,
         5.20000000e+01,   8.00000000e-01,   5.54000000e+00,
         1.16500000e+01,   6.99900000e+01,   1.00000000e+00])
array([[  2.01600000e+03,   1.00000000e+00],
       [  2.01600000e+03,   1.00000000e+00]])


In [56]:
pp(taxi_ten[[0,1,3],0:3]) # subset specific rows and specific columns with numeric indexing

array([[  2.01600000e+03,   1.00000000e+00,   1.00000000e+00],
       [  2.01600000e+03,   1.00000000e+00,   1.00000000e+00],
       [  2.01600000e+03,   1.00000000e+00,   1.00000000e+00]])


In [57]:
row_0 = taxi[0,:]
rows_391_to_500 = taxi[391:501,:] #inclusive
row_21_column_5 = taxi[21, 5]

columns_1_4_7=taxi[:,[1,4,7]]
row_99_columns_5_to_8=taxi[99,5:9] #inclusing for column
rows_100_to_200_column_14=taxi[100:201,14]

In [58]:
## math ops for each array element 
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]
trip_length_hours = trip_length_seconds / 3600
trip_mph = trip_distance_miles / trip_length_hours
trip_mph_a = np.divide(trip_distance_miles,  trip_length_hours) #same as above with formal syntax

pp(trip_mph[0:3])
pp(trip_mph_a[0:3])
pp(trip_mph == trip_mph_a)

array([ 37.11340206,  38.58157895,  31.27222982])
array([ 37.11340206,  38.58157895,  31.27222982])
array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)


In [59]:
##statistic ops  noa column
mph_mean=trip_mph.mean()
mph_max=trip_mph.max()
mph_min=trip_mph.min()
mph_sum=trip_mph.sum()
#mph_median=trip_mph.median() #method does not exist
import statistics as s
mph_median=s.median(trip_mph) #method does not exist




In [60]:
taxi.max(axis=0) #columns max max for each column

array([  2.01600000e+03,   6.00000000e+00,   3.10000000e+01,
         7.00000000e+00,   5.00000000e+00,   6.00000000e+00,
         7.00000000e+00,   1.82900000e+02,   8.63830000e+04,
         4.00000000e+02,   6.30000000e+00,   8.05540000e+02,
         1.00000000e+02,   8.34840000e+02,   4.00000000e+00])

In [61]:
taxi.max(axis=1) #rows max  (max for each row)

array([ 2037.,  2016.,  2016., ...,  2822.,  2016.,  2016.])

In [62]:
#concatenate a row to a numpy 2d arr
ones = np.array([
        [1,1,1,1],
        [1,1,1,1]
      ])

zeros = np.array([ 0, 0, 0, 0])
zeros_2d = np.expand_dims(zeros,axis=0)

rowbound = np.concatenate([ones,zeros_2d],axis=0)

pp(rowbound)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0]])


In [63]:
#concatenate a column to a numpy 2d arr
tens = np.array([10,11])
tens_2d = np.expand_dims(tens,axis=1)
colbound = np.concatenate([ones, tens_2d], axis=1)
colbound

array([[ 1,  1,  1,  1, 10],
       [ 1,  1,  1,  1, 11]])

In [64]:
#adding a column to taxi dataset
trip_mph_2d = np.expand_dims(trip_mph,axis=1)
taxi = np.concatenate([taxi,trip_mph_2d],axis=1)

In [65]:
#sorting np array on given column
i_sq = np.array([[5,2,8,3,4],[2,8,6,2,5],[1,6,2,7,7],[0,7,7,4,5],[5,7,1,1,2]])

idx_srt = np.argsort(i_sq[:,4]) #on 4rth column
pp(i_sq)
pp(i_sq[idx_srt])

array([[5, 2, 8, 3, 4],
       [2, 8, 6, 2, 5],
       [1, 6, 2, 7, 7],
       [0, 7, 7, 4, 5],
       [5, 7, 1, 1, 2]])
array([[5, 7, 1, 1, 2],
       [5, 2, 8, 3, 4],
       [2, 8, 6, 2, 5],
       [0, 7, 7, 4, 5],
       [1, 6, 2, 7, 7]])


In [66]:
##sorting taxi on last column (added trip_mph")
ix = np.argsort(-taxi[:,15])  #minus in front of taxi means sort in desc order
taxi_sorted_by_avgspeed = taxi[ix]

pp(taxi_sorted_by_avgspeed[0:2,])

array([[  2.01600000e+03,   1.00000000e+00,   2.20000000e+01,
          5.00000000e+00,   3.00000000e+00,   2.00000000e+00,
          2.00000000e+00,   2.30000000e+01,   1.00000000e+00,
          2.50000000e+00,   8.00000000e-01,   0.00000000e+00,
          0.00000000e+00,   3.30000000e+00,   2.00000000e+00,
          8.28000000e+04],
       [  2.01600000e+03,   2.00000000e+00,   1.30000000e+01,
          6.00000000e+00,   3.00000000e+00,   2.00000000e+00,
          2.00000000e+00,   1.96000000e+01,   1.00000000e+00,
          2.50000000e+00,   8.00000000e-01,   0.00000000e+00,
          0.00000000e+00,   3.30000000e+00,   2.00000000e+00,
          7.05600000e+04]])


#### Numpy boolean indexing

In [67]:
taxi = np.genfromtxt('nyc_taxis.csv', delimiter=',')  #same dataset as before
taxi.dtype 
taxi = taxi[1:,] #strip off 0th row with header

In [68]:
# how to filter on a column
i_sq = np.array([[5,2,8,3,4],[2,8,6,2,5],[1,6,2,7,7],[0,7,7,4,5],[5,7,1,1,2]])
pp(i_sq)
ix = i_sq[:,4] < 5 # we sort on the last column, index = 4, it produces a boolean filter
i_sq_filtered = i_sq[ix]
print('afer filtering  on 4rth column')
pp(i_sq_filtered)

array([[5, 2, 8, 3, 4],
       [2, 8, 6, 2, 5],
       [1, 6, 2, 7, 7],
       [0, 7, 7, 4, 5],
       [5, 7, 1, 1, 2]])
afer filtering  on 4rth column
array([[5, 2, 8, 3, 4],
       [5, 7, 1, 1, 2]])


In [69]:
taxi_head = ['pickup_year','pickup_month','pickup_day','pickup_dayofweek','pickup_time','pickup_location_code','dropoff_location_code','trip_distance','trip_length','fare_amount','fees_amount','tolls_amount','tip_amount','total_amount','payment_type']
pickup_month_ix = taxi_head.index('pickup_month')
pickup_month = taxi[:,pickup_month_ix] #2nd column of the whole dataset

january_bool = pickup_month == 1 #creates a bool index
january = pickup_month[january_bool]  # elements fro all pickup months only from january

january.shape
january_rides = january.shape[0] # get number of rows (vec lenght) = number of raids in jan
print('raids in january:{}'.format(january_rides))

raids in january:13481


In [70]:
#indexes on 0th or 1st dimension
arr = np.array( [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

bl_1 = [True, False, True, True]
pp(arr[bl_1]) #index on rows

pp('index on columns')
bl_2 = [False, True, True]
pp(arr[:,bl_2]) # filter specific columns

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])
'index on columns'
array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])


In [71]:
## how to filter out tax data rows with unrealistic speeds

trip_mph = taxi[:,7] / ( taxi[:,8] / 3600 )
trip_mph_bl = trip_mph > 10000 #filter

trips_over_high = taxi[trip_mph_bl,5:9] #subcolumns 5 to 9
pp(trips_over_high)
pp(taxi_head[5:9])

array([[  2. ,   2. ,  19.3,   5. ],
       [  2. ,   2. ,  21.4,   7. ],
       [  2. ,   2. ,  12.4,   4. ],
       [  2. ,   2. ,  23. ,   1. ],
       [  2. ,   2. ,  19.6,   1. ],
       [  2. ,   2. ,  17.3,   4. ],
       [  3. ,   3. ,  20.6,   6. ],
       [  2. ,   2. ,  11.7,   3. ],
       [  2. ,   2. ,  17.2,   5. ],
       [  2. ,   2. ,  16.6,   5. ],
       [  2. ,   2. ,  16.7,   2. ],
       [  3. ,   3. ,  17.8,   2. ],
       [  2. ,   2. ,  17.2,   2. ],
       [  2. ,   2. ,  19.8,   4. ],
       [  2. ,   2. ,   9.6,   3. ],
       [  2. ,   2. ,   8.6,   3. ],
       [  2. ,   2. ,  17.7,   5. ],
       [  3. ,   3. ,  16.9,   3. ],
       [  2. ,   2. ,  17.9,   6. ],
       [  2. ,   2. ,  11.6,   3. ],
       [  3. ,   3. ,   8.8,   3. ],
       [  2. ,   2. ,  11.7,   4. ],
       [  2. ,   2. ,  10.7,   3. ],
       [  2. ,   2. ,  15.8,   5. ],
       [  2. ,   2. ,  18.7,   4. ],
       [  2. ,   2. ,   8.7,   3. ],
       [  2. ,   2. ,  27.1,   4. ]])


In [72]:
##find rows with highest tip amounts
tips = taxi[:,12]
tip_bool = tips > 50
top_tips = taxi[tip_bool, 5:14]
pp(top_tips[0:2,])

array([[  4.00000000e+00,   2.00000000e+00,   2.14500000e+01,
          2.00400000e+03,   5.20000000e+01,   8.00000000e-01,
          0.00000000e+00,   5.28000000e+01,   1.05600000e+02],
       [  3.00000000e+00,   4.00000000e+00,   9.20000000e+00,
          1.04100000e+03,   2.70000000e+01,   1.30000000e+00,
          5.54000000e+00,   6.00000000e+01,   9.38400000e+01]])


In [73]:
taxi_modified = taxi.copy()

taxi_modified[28214,5] = 1 #modify dataset cell
taxi_modified[:,0] = 16 #modify dataset 1st column
taxi_modified[1800:1802,7] = taxi_modified[:,7].mean()

In [74]:
#assign values based on filter
a = np.array([1, 2, 3, 4, 5])
a[a>2] = 99
pp(a)

array([ 1,  2, 99, 99, 99])


In [75]:
#how to assign values to specific column, based on filter
c = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


#first column c[:,1]>2 is a filter
c[c[:,1] > 2, 1] = 99 #assign to 2nd column a value based on filter on 1st col
pp(c)

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7, 99,  9]])


In [76]:
##challenges
jfk=taxi[taxi[:,5]==2,:] # 2 is id of jfk
laguardia=taxi[taxi[:,5]==3,:]  # 4 is id of laguardia
newark=taxi[taxi[:,5]==5,:] #  5 is id of newwark

jfk_count = taxi[taxi[:,6]==2,:].shape[0]
laguardia_count = taxi[taxi[:,6]==3,:].shape[0]
newark_count = taxi[taxi[:,6]==5,:].shape[0]

pp('taxi travels to jfk:{}'.format(jfk_count))
pp('taxi travels to laguardia:{}'.format(laguardia_count))
pp('taxi travels to newwark:{}'.format(newark_count))

'taxi travels to jfk:11832'
'taxi travels to laguardia:16602'
'taxi travels to newwark:63'


In [77]:
##challenge to remove the bad data
trip_mph = taxi[:,7] / ( taxi[:,8] / 3600 )
cleaned_taxi = taxi[trip_mph < 100,:]  #safe to assume that travels < 100 miles

notcleaned_mean_distance = taxi[:,7].mean()
mean_distance = cleaned_taxi[:,7].mean()
mean_length   = cleaned_taxi[:,8].mean()
mean_total_amount   = cleaned_taxi[:,13].mean()
mean_mph   = trip_mph[trip_mph < 100].mean()

pp('uncleaned {} mean distance vs cleaned {} mean distance'.format(notcleaned_mean_distance,mean_distance))

('uncleaned 12.6674260830728 mean distance vs cleaned 12.666396599932893 mean '
 'distance')


## PANDAS

In [78]:
import pandas as pd

In [79]:
def load_header(filename, separator=','):
    cols = []
    with open(filename, mode="rt", encoding='utf-8') as f:
        chars = [line.split('\n')[0] for line in f.readlines()[0]]
    gchars = ''.join(chars)
    cols = gchars.split(separator)
    return cols

def get_colidx(colname, columns):
    ix = columns.index(colname)   # index()  api of list
    return ix

In [80]:
fn="f500.csv"
dt_head=load_header(fn)
pp(dt_head)

['company',
 'rank',
 'revenues',
 'revenue_change',
 'profits',
 'assets',
 'profit_change',
 'ceo',
 'industry',
 'sector',
 'previous_rank',
 'country',
 'hq_location',
 'website',
 'years_on_global_500_list',
 'employees',
 'total_stockholder_equity']


In [81]:
pp(get_colidx("profits", dt_head))

4


### loading df from csv specifying index column

In [82]:

f500 = pd.read_csv(fn, index_col=0) # !here is what you defined as index!!
#company column will be used as index

In [83]:
f500_type = type(f500)
f500_shape = f500.shape
pp(f500_shape)

pp(f500.info()) #summary of columns

(500, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
rank                        500 non-null int64
revenues                    500 non-null int64
revenue_change              498 non-null float64
profits                     499 non-null float64
assets                      500 non-null int64
profit_change               436 non-null float64
ceo                         500 non-null object
industry                    500 non-null object
sector                      500 non-null object
previous_rank               500 non-null int64
country                     500 non-null object
hq_location                 500 non-null object
website                     500 non-null object
years_on_global_500_list    500 non-null int64
employees                   500 non-null int64
total_stockholder_equity    500 non-null int64
dtypes: float64(3), int64(7), object(6)
memory usage: 66.4+ KB
None


In [84]:
f500_head = f500.head(2)
f500_tail = f500.tail(2)
pp(f500_head)

            rank  revenues  revenue_change  profits  assets  profit_change  \
company                                                                      
Walmart        1    485873             0.8  13643.0  198825           -7.2   
State Grid     2    315199            -4.4   9571.3  489838           -6.2   

                            ceo               industry     sector  \
company                                                             
Walmart     C. Douglas McMillon  General Merchandisers  Retailing   
State Grid              Kou Wei              Utilities     Energy   

            previous_rank country      hq_location                 website  \
company                                                                      
Walmart                 1     USA  Bentonville, AR  http://www.walmart.com   
State Grid              2   China   Beijing, China  http://www.sgcc.com.cn   

            years_on_global_500_list  employees  total_stockholder_equity  
company              

In [85]:
#accessing subcolumns
industries = f500.loc[:,'industry'] #1 column
#selected columns
previous = f500.loc[:,['rank','previous_rank','years_on_global_500_list']]
#selected columns with numeric indexes
financial_data = f500.iloc[:,1:6]

In [86]:
ceos = f500["ceo"] #get one column
walmart = ceos['Walmart']
apple_to_samsung = ceos['Apple':'Samsung Electronics']
oil_companies = ceos[['Exxon Mobil','BP', 'Chevron']]
pp(oil_companies)

company
Exxon Mobil     Darren W. Woods
BP             Robert W. Dudley
Chevron          John S. Watson
Name: ceo, dtype: object


In [87]:
#access specific index names
drink_companies = f500.loc[["Anheuser-Busch InBev", "Coca-Cola", "Heineken Holding"]]
big_movers = f500.loc[['Aviva','HP','JD.com','BHP Billiton']]
middle_companies=f500.loc['Tata Motors':'Nationwide',["rank", "country"]]
#pp(big_movers)

In [88]:
## describe() on column gives summary statistics
profits_desc = f500.profits.describe()
f500.describe()  #how to get summary stats on whole dataset

rank       revenues  revenue_change       profits        assets  \
count  500.000000     500.000000      498.000000    499.000000  5.000000e+02   
mean   250.500000   55416.358000        4.538353   3055.203206  2.436323e+05   
std    144.481833   45725.478963       28.549067   5171.981071  4.851937e+05   
min      1.000000   21609.000000      -67.300000 -13038.000000  3.717000e+03   
25%    125.750000   29003.000000       -5.900000    556.950000  3.658850e+04   
50%    250.500000   40236.000000        0.550000   1761.600000  7.326150e+04   
75%    375.250000   63926.750000        6.975000   3954.000000  1.805640e+05   
max    500.000000  485873.000000      442.300000  45687.000000  3.473238e+06   

       profit_change  previous_rank  years_on_global_500_list     employees  \
count     436.000000     500.000000                500.000000  5.000000e+02   
mean       24.152752     222.134000                 15.036000  1.339983e+05   
std       437.509566     146.941961                  7.932752  1.700878e+05   
min      -793.700000       0.000000                  1.000000  3.280000e+02   
25%       -22.775000      92.750000                  7.000000  4.293250e+04   
50%        -0.350000     219.500000                 17.000000  9.291050e+04   
75%        17.700000     347.250000                 23.000000  1.689172e+05   
max      8909.500000     500.000000                 23.000000  2.300000e+06   

       total_stockholder_equity  
count                500.000000  
mean               30628.076000  
std                43642.576833  
min               -59909.000000  
25%                 7553.750000  
50%                15809.500000  
75%                37828.500000  
max               301893.000000

In [110]:
#record counts
cnt=f500["country"].value_counts()
cnt.head(10)
#np.array(cnt)

USA            132
China          109
Japan           51
France          29
Germany         29
Britain         24
South Korea     15
Netherlands     14
Switzerland     14
Canada          11
Name: country, dtype: int64

In [90]:
##unique values 
lst_ctries=f500["country"].unique()
lst_ctries[0:5] #fist 5 countries

array(['USA', 'China', 'Japan', 'Germany', 'Netherlands'], dtype=object)

In [91]:
f500.min(numeric_only=True)
f500.median(numeric_only=True)
f500.max(numeric_only=True)

rank                            500.0
revenues                     485873.0
revenue_change                  442.3
profits                       45687.0
assets                      3473238.0
profit_change                  8909.5
previous_rank                   500.0
years_on_global_500_list         23.0
employees                   2300000.0
total_stockholder_equity     301893.0
dtype: float64

In [92]:
#adding a derived column
f500["revenues_b"] = f500["revenues"] / 1000
f500.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 17 columns):
rank                        500 non-null int64
revenues                    500 non-null int64
revenue_change              498 non-null float64
profits                     499 non-null float64
assets                      500 non-null int64
profit_change               436 non-null float64
ceo                         500 non-null object
industry                    500 non-null object
sector                      500 non-null object
previous_rank               500 non-null int64
country                     500 non-null object
hq_location                 500 non-null object
website                     500 non-null object
years_on_global_500_list    500 non-null int64
employees                   500 non-null int64
total_stockholder_equity    500 non-null int64
revenues_b                  500 non-null float64
dtypes: float64(4), int64(7), object(6)
memory usage: 90.3+ KB


In [93]:
#make a mask on index
kr_records = f500["country"] == 'South Korea'
#list(kr_records)
f500[kr_records][0:5] # first 5 records with country corea

rank  revenues  revenue_change  profits  assets  \
company                                                                 
Samsung Electronics     15    173957            -2.0  19316.5  217104   
Hyundai Motor           78     80701            -0.8   4659.0  148092   
SK Holdings             95     72579           107.4    659.7   85332   
Korea Electric Power   177     51500            -0.6   6074.1  147265   
LG Electronics         201     47712            -4.6     66.2   31348   

                      profit_change             ceo  \
company                                               
Samsung Electronics            16.8    Oh-Hyun Kwon   
Hyundai Motor                 -17.9  Mong-Koo Chung   
SK Holdings                   -86.0    Tae Won Chey   
Korea Electric Power          -48.3    Hwan-Eik Cho   
LG Electronics                -39.8    Seong-Jin Jo   

                                            industry                  sector  \
company                                                                        
Samsung Electronics   Electronics, Electrical Equip.              Technology   
Hyundai Motor               Motor Vehicles and Parts  Motor Vehicles & Parts   
SK Holdings                       Petroleum Refining                  Energy   
Korea Electric Power                       Utilities                  Energy   
LG Electronics        Electronics, Electrical Equip.              Technology   

                      previous_rank      country                hq_location  \
company                                                                       
Samsung Electronics              13  South Korea         Suwon, South Korea   
Hyundai Motor                    84  South Korea         Seoul, South Korea   
SK Holdings                     294  South Korea         Seoul, South Korea   
Korea Electric Power            172  South Korea  Jeollanam-do, South Korea   
LG Electronics                  180  South Korea         Seoul, South Korea   

                                           website  years_on_global_500_list  \
company                                                                        
Samsung Electronics         http://www.samsung.com                        23   
Hyundai Motor         http://worldwide.hyundai.com                        22   
SK Holdings                    http://www.sk.co.kr                         2   
Korea Electric Power        http://www.kepco.co.kr                        23   
LG Electronics                   http://www.lg.com                        17   

                      employees  total_stockholder_equity  revenues_b  
company                                                                
Samsung Electronics      325000                    154376     173.957  
Hyundai Motor            129315                     55639      80.701  
SK Holdings               84000                     10858      72.579  
Korea Electric Power      43688                     59394      51.500  
LG Electronics            75000                      9926      47.712

In [94]:
##assign values to df based on mask
msk =f500["previous_rank"] == 0
f500.loc[msk,"previous_rank"] = np.nan
pp(f500["previous_rank"].value_counts(dropna=False).head(5))
f500[msk].iloc[:,0:10].head(5)

NaN       33
 471.0     1
 234.0     1
 125.0     1
 166.0     1
Name: previous_rank, dtype: int64


rank  revenues  revenue_change  profits  assets  \
company                                                                   
Legal & General Group     49    105235           442.3   1697.9  577954   
Uniper                    91     74407             NaN  -3557.5   51541   
Dell Technologies        124     64806            18.1  -1672.0  118206   
Anbang Insurance Group   139     60800           124.0   3883.9  430040   
Albertsons Cos.          141     59678             1.6   -373.3   23755   

                        profit_change               ceo  \
company                                                   
Legal & General Group             3.4      Nigel Wilson   
Uniper                            NaN     Klaus Schafer   
Dell Technologies                 NaN   Michael S. Dell   
Anbang Insurance Group            0.9        Wu Xiaohui   
Albertsons Cos.                   NaN  Robert G. Miller   

                                                industry              sector  \
company                                                                        
Legal & General Group    Insurance: Life, Health (stock)          Financials   
Uniper                                            Energy              Energy   
Dell Technologies            Computers, Office Equipment          Technology   
Anbang Insurance Group  Insurance: Life, Health (Mutual)          Financials   
Albertsons Cos.                     Food and Drug Stores  Food & Drug Stores   

                        previous_rank  
company                                
Legal & General Group             NaN  
Uniper                            NaN  
Dell Technologies                 NaN  
Anbang Insurance Group            NaN  
Albertsons Cos.                   NaN

In [95]:
f500.hq_location.value_counts().head(5)

Beijing, China     56
Tokyo, Japan       36
Paris, France      17
New York, NY       15
London, Britain    14
Name: hq_location, dtype: int64

In [96]:
#reread country
fn="f500.csv"
f500 = pd.read_csv(fn, index_col=0)

In [97]:
us_msk = f500["country"] == 'USA'
cities_usa = f500[us_msk].hq_location.value_counts()
pp(cities_usa.head(3))

New York, NY    15
Houston, TX      5
Atlanta, GA      4
Name: hq_location, dtype: int64


In [98]:
sector_china = f500[f500.country == "China"].sector.value_counts()
pp(sector_china.head(5))

Financials                    25
Energy                        22
Wholesalers                    9
Engineering & Construction     8
Technology                     8
Name: sector, dtype: int64


In [99]:
mean_employees_japan = f500[f500.country == "Japan"].employees.mean()
pp(mean_employees_japan)

104564.45098039215


In [112]:
f500.head(5)

rank  revenues  revenue_change  profits  assets  \
company                                                                     
Walmart                      1    485873             0.8  13643.0  198825   
State Grid                   2    315199            -4.4   9571.3  489838   
Sinopec Group                3    267518            -9.1   1257.9  310726   
China National Petroleum     4    262573           -12.3   1867.5  585619   
Toyota Motor                 5    254694             7.7  16899.3  437575   

                          profit_change                  ceo  \
company                                                        
Walmart                            -7.2  C. Douglas McMillon   
State Grid                         -6.2              Kou Wei   
Sinopec Group                     -65.0            Wang Yupu   
China National Petroleum          -73.7        Zhang Jianhua   
Toyota Motor                      -12.3          Akio Toyoda   

                                          industry                  sector  \
company                                                                      
Walmart                      General Merchandisers               Retailing   
State Grid                               Utilities                  Energy   
Sinopec Group                   Petroleum Refining                  Energy   
China National Petroleum        Petroleum Refining                  Energy   
Toyota Motor              Motor Vehicles and Parts  Motor Vehicles & Parts   

                          previous_rank country      hq_location  \
company                                                            
Walmart                               1     USA  Bentonville, AR   
State Grid                            2   China   Beijing, China   
Sinopec Group                         4   China   Beijing, China   
China National Petroleum              3   China   Beijing, China   
Toyota Motor                          8   Japan    Toyota, Japan   

                                               website  \
company                                                  
Walmart                         http://www.walmart.com   
State Grid                      http://www.sgcc.com.cn   
Sinopec Group                   http://www.sinopec.com   
China National Petroleum        http://www.cnpc.com.cn   
Toyota Motor              http://www.toyota-global.com   

                          years_on_global_500_list  employees  \
company                                                         
Walmart                                         23    2300000   
State Grid                                      17     926067   
Sinopec Group                                   19     713288   
China National Petroleum                        17    1512048   
Toyota Motor                                    23     364445   

                          total_stockholder_equity  
company                                             
Walmart                                      77798  
State Grid                                  209456  
Sinopec Group                               106523  
China National Petroleum                    301893  
Toyota Motor                                157210

In [114]:
wcols=['revenues','profits','assets', 'industry','sector','country','employees']
f500[wcols].head(5)

revenues  profits  assets                  industry  \
company                                                                         
Walmart                     485873  13643.0  198825     General Merchandisers   
State Grid                  315199   9571.3  489838                 Utilities   
Sinopec Group               267518   1257.9  310726        Petroleum Refining   
China National Petroleum    262573   1867.5  585619        Petroleum Refining   
Toyota Motor                254694  16899.3  437575  Motor Vehicles and Parts   

                                          sector country  employees  
company                                                              
Walmart                                Retailing     USA    2300000  
State Grid                                Energy   China     926067  
Sinopec Group                             Energy   China     713288  
China National Petroleum                  Energy   China    1512048  
Toyota Motor              Motor Vehicles & Parts   Japan     364445

In [134]:
ctry_grp=f500.groupby(by='country') #grouped object
ctry_grp['revenues'].describe()

count          mean           std      min       25%      50%  \
country                                                                       
Australia       7.0  33688.714286   8747.379221  26032.0  27331.00  30912.0   
Belgium         1.0  45905.000000           NaN  45905.0  45905.00  45905.0   
Brazil          7.0  52024.571429  20676.953175  22167.0  39094.00  57443.0   
Britain        24.0  51588.708333  37814.058963  21741.0  25754.50  36684.5   
Canada         11.0  31848.000000   6098.697369  22943.0  25945.00  34145.0   
China         109.0  55397.880734  47608.309429  21796.0  29877.00  40234.0   
Denmark         1.0  35464.000000           NaN  35464.0  35464.00  35464.0   
Finland         1.0  26113.000000           NaN  26113.0  26113.00  26113.0   
France         29.0  55231.793103  31457.180503  22477.0  28572.00  45249.0   
Germany        29.0  63915.000000  47157.065948  21655.0  35011.00  48204.0   
India           7.0  39993.000000   9142.820498  28166.0  33215.00  40329.0   
Indonesia       1.0  36487.000000           NaN  36487.0  36487.00  36487.0   
Ireland         4.0  32819.500000   4142.277031  28833.0  29688.00  32385.5   
Israel          1.0  21903.000000           NaN  21903.0  21903.00  21903.0   
Italy           7.0  51899.571429  27169.509674  21941.0  34382.00  36617.0   
Japan          51.0  53164.039216  38432.982497  23551.0  30687.00  41620.0   
Luxembourg      1.0  56791.000000           NaN  56791.0  56791.00  56791.0   
Malaysia        1.0  49479.000000           NaN  49479.0  49479.00  49479.0   
Mexico          2.0  54987.500000   3940.706092  52201.0  53594.25  54987.5   
Netherlands    14.0  61708.928571  62163.608357  22873.0  23906.50  39510.5   
Norway          1.0  45873.000000           NaN  45873.0  45873.00  45873.0   
Russia          4.0  65247.750000  21004.778050  42159.0  52954.50  63725.0   
Saudi Arabia    1.0  35421.000000           NaN  35421.0  35421.00  35421.0   
Singapore       3.0  54454.333333  38800.532990  23863.0  32632.50  41402.0   
South Korea    15.0  49725.600000  38587.057795  22207.0  25833.00  40606.0   
Spain           9.0  40600.666667  18870.342154  25733.0  26070.00  34485.0   
Sweden          3.0  27963.666667   6549.211428  22618.0  24311.00  26004.0   
Switzerland    14.0  51353.571429  39823.440658  25112.0  28763.25  35029.0   
Taiwan          6.0  46364.666667  43676.348733  23773.0  26647.75  28551.5   
Thailand        1.0  48719.000000           NaN  48719.0  48719.00  48719.0   
Turkey          1.0  23456.000000           NaN  23456.0  23456.00  23456.0   
U.A.E           1.0  22799.000000           NaN  22799.0  22799.00  22799.0   
USA           132.0  64218.371212  58339.347097  21609.0  28551.75  41325.0   
Venezuela       1.0  24403.000000           NaN  24403.0  24403.00  24403.0   

                   75%       max  
country                           
Australia     38106.00   48003.0  
Belgium       45905.00   45905.0  
Brazil        62484.50   81405.0  
Britain       67504.25  186606.0  
Canada        36328.00   40238.0  
China         62387.00  315199.0  
Denmark       35464.00   35464.0  
Finland       26113.00   26113.0  
France        70517.00  143722.0  
Germany       74407.00  240264.0  
India         45732.00   53562.0  
Indonesia     36487.00   36487.0  
Ireland       35517.00   37674.0  
Israel        21903.00   21903.0  
Italy         70379.00   95217.0  
Japan         61609.50  254694.0  
Luxembourg    56791.00   56791.0  
Malaysia      49479.00   49479.0  
Mexico        56380.75   57774.0  
Netherlands   57912.25  240033.0  
Norway        45873.00   45873.0  
Russia        76018.25   91382.0  
Saudi Arabia  35421.00   35421.0  
Singapore     69750.00   98098.0  
South Korea   49606.00  173957.0  
Spain         43698.00   82801.0  
Sweden        30636.50   35269.0  
Switzerland   52429.25  173883.0  
Taiwan        34265.25  135129.0  
Thailand      48719.00   48719.0  
Turkey        23456.00   23456.0  
U.A.E         

In [126]:
f500[f500.country=='USA']['revenues'].sum()

8476825