### Arithmetics

In [1]:
8/5

1.6

In [2]:
8//5 #arithmetic division

1

In [3]:
print(3**2) #power

9


In [4]:
18 % 7 #modulo

4

In [5]:
##100$ after 7 years at 10%
100*(1+0.1)**7

194.87171000000012

### + operator on numeric and strings

In [6]:
2 +3  

5

In [7]:
'ab' + '_' + 'cd'

'ab_cd'

In [8]:
x = 5 # assign

In [9]:
x

5

In [10]:
desc = 'compound interest' # string
profitable = True  # boolean

In [11]:
type(desc) 

str

In [12]:
type(profitable)

bool

In [13]:
savings = 100
factor = 1.1
nyears = 7
result=savings*factor**nyears
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

I started with $100 and now have $194.87171000000012. Awesome!


### type conversion

In [14]:
x = 10.1 ; print("the actual value of x is " + str(x))

the actual value of x is 10.1


In [15]:
float('3.1415')**2

9.86902225

In [16]:
crit = bool('True')
if crit :  print('this is true')

this is true


In [17]:
print("adding integers like " + str(5) + " to strings works")

adding integers like 5 to strings works


In [18]:
print( "multiplyng strings concatentates them " + ("Hey " * 2))

multiplyng strings concatentates them Hey Hey 


In [19]:
print(True+False)

1


In [20]:
print(False*False)

0


### List data type

In [21]:
l=[1.73, 1.74, -1.88]

In [22]:
l[0]

1.73

In [23]:
type(l)

list

In [24]:
fam=['aa', 1.10, 'bb', "a"*4, True] # list can contain any type

In [25]:
fam

['aa', 1.1, 'bb', 'aaaa', True]

In [26]:
fam2 =[['a',1],['b',2],['c',3]] # list of lists

In [27]:
fam2[0] #subsetting first list element

['a', 1]

In [28]:
fam2[-1] #last element

['c', 3]

In [29]:
fam2[-2] #before last

['b', 2]

In [30]:
fam2[0:2] #a sublist

[['a', 1], ['b', 2]]

In [31]:
fam[1:3] #subseting start:end  start el included, end el not included

[1.1, 'bb']

In [32]:
fam[:2] #first two elements

['aa', 1.1]

In [33]:
fam[-2:] #last two elements

['aaaa', True]

In [34]:
type(fam2)

list

#### higher dimensional list subsetting

In [35]:
x = [["a", "b", "c"], 
     ["d", "e", "f"], 
     ["g", "h", "i"]]

In [36]:
x[2][0]

'g'

In [37]:
x[2][:2]

['g', 'h']

In [38]:
x[2]  #a list (row in matrix)

['g', 'h', 'i']

#### appending new elments

In [39]:
x=['a','b'] 
x = x + ['c', 'd']
x

['a', 'b', 'c', 'd']

In [40]:
del(x[1]) #delete 2nd element in the list
x

['a', 'c', 'd']

#### list references and list copies

In [41]:
x=[1,2]
y=x   # y is a reference to x
x[0]=-1 #so when a data under x changes
y  # the referenced data is changed as well ( 1 copy in memor)

[-1, 2]

In [42]:
z=list(x) # making an explicit copy of x in memory
x[0]= -2  
z  # z is independent from x

[-1, 2]

## Functions

In [43]:
round(1.68, 1)

1.7

In [44]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [45]:
?max #inline help

In [46]:
first = [11.25, 18.0, 20.0]
sorted(first, reverse=True) #sort a list in a reverse order

[20.0, 18.0, 11.25]

### methods

In [47]:
first.append(30.33)
first

[11.25, 18.0, 20.0, 30.33]

In [48]:
first.index(20.0)

2

In [49]:
pdesc="poolhouse"

In [50]:
pdesc.upper()

'POOLHOUSE'

In [51]:
pdesc.count('o')

3

In [52]:
first.remove(11.25) # change first
first

[18.0, 20.0, 30.33]

In [53]:
first.reverse() #change first
first

[30.33, 20.0, 18.0]

## how to check variables at current stack

In [109]:
whos

Variable     Type                          Data/Info
----------------------------------------------------
array        builtin_function_or_method    <built-in function array>
bmi          ndarray                       2: 2 elems, type `float64`, 16 bytes
circ_air     float                         12.566370614359172
crit         bool                          True
desc         str                           compound interest
factor       float                         1.1
fam          list                          n=5
fam2         list                          n=3
first        list                          n=3
height       ndarray                       5000: 5000 elems, type `float64`, 40000 bytes
l            list                          n=3
math         module                        <module 'math' from '/Use<...>h.cpython-35m-darwin.so'>
np           module                        <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
np_city      ndarray                       5000x2: 1

## Packages

pkg/
    module1.py
    module2.py

use pip tool to install package  

ex %>pip3 install numpy

In [2]:
import numpy  as np # to import a package with a short prefix name

In [55]:
np.array([1,2,3]) # prefix is used

array([1, 2, 3])

In [56]:
from numpy import array #import a specific function from package , use with no prefix

In [57]:
array([4,5,6])

array([4, 5, 6])

In [58]:
import math

In [59]:
radius=2.0
circ_air=math.pi * radius**2
circ_air

12.566370614359172

### Numpy package (numeric python)

In [60]:
np_height=np.array([1.73,1.68]) #numpy arrays contain only one time
np_weight=np.array([65.4,59.2])
bmi=np_weight / np_height **2   # operation performed on each element of lists in the formula
bmi

array([ 21.85171573,  20.97505669])

In [63]:
bmi[bmi > 21.0]

array([ 21.85171573])

### 2D  numpy arrays

In [71]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

In [77]:
np_mat[0,:] #access top row

array([1, 2])

In [78]:
np_mat[-1,:] #access bottow row

array([5, 6])

In [82]:
np_mat[:,0] #access the first column

array([1, 3, 5])

In [92]:
np_mat[:,1] #access of the 2nd column

array([2, 4, 6])

In [85]:
np_mat + 10 #add to each element 10

array([[11, 12],
       [13, 14],
       [15, 16]])

In [88]:
np_mat + np.array([10,10]) #same result as above

array([[11, 12],
       [13, 14],
       [15, 16]])

In [89]:
np_mat**2  ## multiply each element by itself

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [91]:
np_mat * np.array([2,3]) # multiply each row in array by a second array element by element

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

### Basic status on numpy arrays

In [95]:
height = np.round(np.random.normal(1.75, 0.20, 5000),2) # generate an array from  normal dist
# 1.75 is mean, 0.20 is stdev 5000 is number of samples

In [99]:
np.mean(height)


1.7567340000000005

In [100]:
np.median(height)

1.75

In [101]:
np.std(height)

0.20039988334327941

In [104]:
np.sort(height) # sorts all elements

array([ 1.03,  1.08,  1.11, ...,  2.37,  2.37,  2.4 ])

In [105]:
np.sum(height) #sums elements

8783.6700000000019

#### how to colbind two columns in array

In [106]:
weight = np.round(np.random.normal(60.32, 15, 5000),2)

In [107]:
np_city = np.column_stack((height,weight))

In [108]:
np_city

array([[  1.93,  49.83],
       [  1.9 ,  65.17],
       [  2.15,  53.48],
       ..., 
       [  2.  ,  71.13],
       [  2.17,  86.12],
       [  1.42,  63.86]])

### subsetting np arrays

In [3]:
categ = np.array(['B', 'G', 'B', 'G', 'B']) # a group of boys and girls

In [5]:
height = np.array([170, 165, 164, 166, 172]) # their respective height

In [7]:
categ=='B'  ## this makes an index selecting only boys

array([ True, False,  True, False,  True], dtype=bool)

In [9]:
height[categ=='B'] ## heighs of only boys

array([170, 164, 172])

In [10]:
np.median(height[categ=='B']) #median of boys height

170.0

In [11]:
np.median(height[categ=='G']) ## median of girls height

165.5

#### this finishes the datacamp course Introduction to Python